project_id = "qczpaylewyhkpbjkilrw"

[functions.calculate-shipping-cost]
verify_jwt = true

[functions.create-offer]
verify_jwt = true

[functions.accept-offer]
verify_jwt = false

[functions.confirm-delivery]
verify_jwt = true

[functions.cancel-order]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.update-shipment]
verify_jwt = true