// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qczpaylewyhkpbjkilrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjenBheWxld3loa3BiamtpbHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTM3NDIsImV4cCI6MjA3MTE4OTc0Mn0.XZ--C9tAn1Y3irx3_fVnbxIvBviw5O3Jcj_J4ePC6ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});